image: fedora:latest

stages:
  - build

before_script:
  - uname -a && cat /etc/os-release

build:
  stage: build
  tags:
    - linux
  script:
    - dnf install -y xorriso
    - ./build.sh
  artifacts:
    untracked: true
    expire_in: 6 mos
